### ISSUE TITLE
after running the deployment on an AIO I get this error on both osds

### ISSUE THREAD

**Issue by letterj** [rcbops/rpc-ceph#28]
unable to find a keyring on /etc/ceph/ceph.client.admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
2017-11-21 15:03:55.604176 7f146e450700 -1 monclient: authenticate NOTE: no keyring found; disabled cephx authentication
2017-11-21 15:03:55.604195 7f146e450700  0 librados: client.admin authentication error (95) Operation not supported

**Comment by letterj** [comment]
Right now you will need the admin key on the osd's.  So we might need to deploy the admin key on every osd server.

**Comment by andymcc** [comment]
I'm personally against doing this, although we can set that up by adding:
copy_admin_key: True

to the playbooks/group_vars/all.yml

OSDs/RGWs shouldn't need the admin key so giving it to them seems like an odd approach for a prod system.
