### ISSUE TITLE
rsyslog error after deployment

### ISSUE THREAD

**Issue by letterj** [rcbops/rpc-ceph#29]
fatal: [osd1 -> 10.1.1.1]: FAILED! => {"changed": false, "cmd": "ls /var/log/rsyslog/osd1/ceph-osd.*.log | wc -l", "delta": "0:00:00.004398", "end": "2017-11-20 22
:10:05.279580", "failed": true, "failed_when_result": true, "rc": 0, "start": "2017-11-20 22:10:05.275182", "stderr": "", "stderr_lines": [], "stdout": "5", "stdou
t_lines": ["5"]}
fatal: [osd2 -> 10.1.1.1]: FAILED! => {"changed": false, "cmd": "ls /var/log/rsyslog/osd2/ceph-osd.*.log | wc -l", "delta": "0:00:00.003299", "end": "2017-11-20 22
:10:05.291139", "failed": true, "failed_when_result": true, "rc": 0, "start": "2017-11-20 22:10:05.287840", "stderr": "", "stderr_lines": [], "stdout": "5", "stdou
t_lines": ["5"]}
fatal: [allsvc -> 10.1.1.1]: FAILED! => {"changed": false, "cmd": "ls /var/log/rsyslog/allsvc/ceph-osd.*.log | wc -l", "delta": "0:00:00.003079", "end": "2017-11-2
0 22:10:05.324207", "failed": true, "failed_when_result": true, "rc": 0, "start": "2017-11-20 22:10:05.321128", "stderr": "", "stderr_lines": [], "stdout": "4", "s
tdout_lines": ["4"]}

**Comment by andymcc** [comment]
This is a result of how the rsyslog role works upstream, we should probably get that fixed - unfortunately there is a race condition where it checks for existing logs to copy over, if the log doesnt exist yet it won't ship it unless you re-run the script.

We could perhaps:
* Rerun the script on a cron schedule
* Look at some way to wildcard the logs instead
* Some things can be done with systemd logging - that may be a deeper hole though.
